[package]
name = "curve-sampler"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
curve-core = { path = "../core" }
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["opengl"] }
log = "0.4"
parking_lot = "0.12"
rustfft = "6"
